### ISSUE TITLE
Screens of offers, needs, members, ...

### ISSUE THREAD

**Issue by edumag** [komunitin/komunitin#49]
Follow jsonapi standard.

https://jsonapi.org

**Comment by estevebadia** [comment]
Aunque pasa el test, me salta esta excepción que quizás estaría bien identificar y arreglar!
**Cannot read property 'coordinates' of undefined**
No te salta a tí?

```
  ● Console

    console.debug src/services/mirage.js:12
      Mirage activated
    console.error node_modules/vue/dist/vue.common.dev.js:630
      [Vue warn]: Error in render: "TypeError: Cannot read property 'coordinates' of undefined"

      found in

      ---> <Group>
             <Root>
    console.error node_modules/vue/dist/vue.common.dev.js:1893
      TypeError: Cannot read property 'coordinates' of undefined
          at VueComponent.center (C:\Users\Personal\projects\komunitin\src\pages\groups\Group.vue:181:1)
          at Watcher.get (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4474:25)
          at Watcher.evaluate (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4579:21)
          at Proxy.computedGetter (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4828:17)
          at Proxy.render (C:\Users\Personal\projects\komunitin\src\pages\groups\Group.vue:395:3680)
          at VueComponent.Vue._render (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:3547:22)
          at VueComponent.updateComponent (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4063:21)
          at Watcher.get (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4474:25)
          at Watcher.run (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4549:22)
          at flushSchedulerQueue (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:4307:13)
          at Array.<anonymous> (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:1985:12)
          at flushCallbacks (C:\Users\Personal\projects\komunitin\node_modules\vue\dist\vue.common.dev.js:1911:14)

```

**Comment by edumag** [comment]
Lo miro.

**Comment by edumag** [comment]
A mí no me salta.
